posts:
  index:
    featured_tag: 'freshlivinglab'
social_media:
  instagram: ''
  facebook: ''
  youtube: ''
  twitter: ''
  linkedin: ''
footer:
  links:
    first:
      title: ''
      link: ''
    second:
      title: ''
      link: ''
    third:
      title: ''
      link: ''
    fourth:
      title: ''
      link: ''
    fifth:
      title: ''
      link: ''