--- !ruby/hash:ActionController::Parameters
posts: !ruby/hash:ActionController::Parameters
  index: !ruby/hash:ActionController::Parameters
    featured_tag: Aspirational Objects
social_media: !ruby/hash:ActionController::Parameters
  instagram: https://instagram.com/space10_journal/
  facebook: ''
  youtube: http://youtube.space10.io
  twitter: https://twitter.com/space10_journal/
  linkedin: https://linkedin.com/company/space-10
footer: !ruby/hash:ActionController::Parameters
  links: !ruby/hash:ActionController::Parameters
    first: !ruby/hash:ActionController::Parameters
      title: About
      link: https://www.space10.io/about
    second: !ruby/hash:ActionController::Parameters
      title: Press
      link: http://press.space10.io
    third: !ruby/hash:ActionController::Parameters
      title: Contact
      link: mailto:discover@space10.io
    fourth: !ruby/hash:ActionController::Parameters
      title: ''
      link: ''
    fifth: !ruby/hash:ActionController::Parameters
      title: ''
      link: ''
