FACEBOOK_KEY: '123'
FACEBOOK_SECRET: '123'

LINKEDIN_KEY: '123'
LINKEDIN_SECRET: '123'

AWS_ACCESS_KEY_ID: '123'
AWS_SECRET_ACCESS_KEY: '123'
AWS_S3_BUCKET: '123'

API_USER: '123'
API_SECRET: '123'

INSTAGRAM_CLIENT_ID: '123'
INSTAGRAM_ACCESS_TOKEN: '123'

MANDRILL_USERNAME: '123'
MANDRILL_PASSWORD: '123'

ADMIN_MODE: 'false'

GA_ID: '123'

PARSE_APP_ID: '123'
PARSE_API_KEY: '123'

GOOGLE_API_KEY: '123'

NEWRELIC_LICENSE: '123'