FACEBOOK_KEY: '400223483511470'
FACEBOOK_SECRET: '8a417bf175d4cac1e39fe02eefd30a43'

AWS_ACCESS_KEY_ID: 'AKIAJML7KURUR5VYHVZA'
AWS_SECRET_ACCESS_KEY: '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'
AWS_S3_BUCKET: 'space10-images'